### ISSUE TITLE
How to retrieve the countries?

### ISSUE THREAD

**Issue by MrMooky** [lwwcas/old-laravel-countries#4]
The README does not specify how to retrieve a list of countries within the Controller. I was hoping for something like `Countries::get();`

Could you please give me a hint? It's also not clear how to combine with `laravel-translatable`.

**Comment by lwwcas** [comment]
Hello @MrMooky , 
Firstly, I'll really be improving the README and I'm going to work this week on documentation.
I've thought of my projects, but if this will help more people, I'll focus on documenting everything.

Now with the `Countries::get()`; question, in this situation you can call Model Country, and handle the same way as any other Model, for example `Country::all()`;
In [Models](https://github.com/lwwcas/laravel-countries/tree/master/src/Models), you will find the Models and can have a sense of what they offer.

The `laravel-translatable`, already combined, everything you find in the [documentation](https://github.com/dimsav/laravel-translatable) will work with the Models.

Remembering that at the moment, I am only working with English and Portuguese, as soon as possible, I will be adding other languages.
